DROP TABLE IF EXISTS IPs;
CREATE TABLE IPs(
ip VARCHAR(20) PRIMARY KEY,
peligro INT NOT NULL DEFAULT 0,
baneos INT NOT NULL DEFAULT 0,
last_ban TIMESTAMP,
malicious_count INT DEFAULT 0
);

DROP TABLE IF EXISTS Peticiones;
CREATE TABLE Peticiones(
id INT PRIMARY KEY AUTO_INCREMENT,
ip VARCHAR(20),
method VARCHAR(20) NOT NULL,
uri VARCHAR(2000) NOT NULL DEFAULT "/",
version VARCHAR(10) NOT NULL DEFAULT "HTTP/1.1",
status INT NOT NULL,
req_bytes INT NOT NULL,
user_agent VARCHAR(1000),
timestamp VARCHAR(40) DEFAULT TIMESTAMP(NOW()),
CONSTRAINT fk_cod_ip FOREIGN KEY (ip) REFERENCES IPs (ip)
);

DROP TABLE IF EXISTS Baneos;
CREATE TABLE Baneos (
id INT PRIMARY KEY AUTO_INCREMENT,
ip VARCHAR(20),
ban_time INT NOT NULL DEFAULT 1,
timestamp VARCHAR(40) DEFAULT TIMESTAMP(NOW()),
CONSTRAINT fk_baneos_ip FOREIGN KEY (ip) REFERENCES IPs (ip)
);